/**
 * pages/DeepLearning.jsx – DL pipeline overview + Colab notebook export
 *
 * No heavy training runs on the server.  Instead this page:
 *   1. Explains the recommended workflow
 *   2. Provides a download of a Colab-ready 3-D U-Net / CNN training notebook
 */
import { useState } from 'react'

const COLAB_NOTEBOOK = {
  nbformat: 4,
  nbformat_minor: 5,
  metadata: {
    kernelspec: { display_name: 'Python 3', language: 'python', name: 'python3' },
    language_info: { name: 'python', version: '3.10.0' },
    colab: { name: 'MedVision_3D_CNN_Training.ipynb', provenance: [] },
  },
  cells: [
    {
      cell_type: 'markdown', metadata: {}, id: 'title',
      source: ['# MedVision – 3D CNN / U-Net Training Template\n',
        'Generated by MedVision. Follow the steps below to train a model on your exported patches.\n'],
    },
    {
      cell_type: 'markdown', metadata: {}, id: 'step1',
      source: ['## Step 1 – Install dependencies'],
    },
    {
      cell_type: 'code', metadata: {}, id: 'install', outputs: [], execution_count: null,
      source: ['!pip install torch torchvision monai numpy matplotlib --quiet'],
    },
    {
      cell_type: 'markdown', metadata: {}, id: 'step2',
      source: ['## Step 2 – Load exported patches'],
    },
    {
      cell_type: 'code', metadata: {}, id: 'load', outputs: [], execution_count: null,
      source: [
        'import numpy as np\n',
        'from google.colab import files\n\n',
        '# Upload your patches_*.npz file when prompted\n',
        'uploaded = files.upload()\n',
        'fname = list(uploaded.keys())[0]\n',
        'data    = np.load(fname)\n',
        'patches = data["patches"]   # float32  (N, P, P, P)\n',
        'coords  = data["coords"]    # int32    (N, 3)\n',
        'spacing = data["spacing"]   # mm/voxel\n',
        'print(f"Loaded {len(patches)} patches of shape {patches[0].shape}")\n',
        'print(f"Spacing: {spacing} mm")',
      ],
    },
    {
      cell_type: 'markdown', metadata: {}, id: 'step3',
      source: ['## Step 3 – Simple 3-D CNN classifier skeleton'],
    },
    {
      cell_type: 'code', metadata: {}, id: 'model', outputs: [], execution_count: null,
      source: [
        'import torch\n',
        'import torch.nn as nn\n\n',
        'class Simple3DCNN(nn.Module):\n',
        '    def __init__(self, n_classes=2):\n',
        '        super().__init__()\n',
        '        self.encoder = nn.Sequential(\n',
        '            nn.Conv3d(1, 16, 3, padding=1), nn.BatchNorm3d(16), nn.ReLU(),\n',
        '            nn.MaxPool3d(2),\n',
        '            nn.Conv3d(16, 32, 3, padding=1), nn.BatchNorm3d(32), nn.ReLU(),\n',
        '            nn.MaxPool3d(2),\n',
        '            nn.Conv3d(32, 64, 3, padding=1), nn.BatchNorm3d(64), nn.ReLU(),\n',
        '            nn.AdaptiveAvgPool3d(1),\n',
        '        )\n',
        '        self.head = nn.Linear(64, n_classes)\n\n',
        '    def forward(self, x):\n',
        '        x = self.encoder(x).flatten(1)\n',
        '        return self.head(x)\n\n',
        '# Instantiate\n',
        'model = Simple3DCNN(n_classes=2)\n',
        'print(model)',
      ],
    },
    {
      cell_type: 'markdown', metadata: {}, id: 'step4',
      source: ['## Step 4 – MONAI 3-D U-Net skeleton (segmentation)'],
    },
    {
      cell_type: 'code', metadata: {}, id: 'unet', outputs: [], execution_count: null,
      source: [
        'from monai.networks.nets import UNet\n\n',
        'unet = UNet(\n',
        '    spatial_dims=3,\n',
        '    in_channels=1,\n',
        '    out_channels=2,        # background + foreground\n',
        '    channels=(16, 32, 64, 128),\n',
        '    strides=(2, 2, 2),\n',
        '    num_res_units=2,\n',
        ')\n',
        'print(unet)',
      ],
    },
    {
      cell_type: 'markdown', metadata: {}, id: 'step5',
      source: ['## Step 5 – Training loop template'],
    },
    {
      cell_type: 'code', metadata: {}, id: 'train', outputs: [], execution_count: null,
      source: [
        'import torch.optim as optim\n',
        'from torch.utils.data import DataLoader, TensorDataset\n\n',
        '# ── Dummy labels – replace with your real labels ────────────────\n',
        'X = torch.tensor(patches[:, None], dtype=torch.float32)  # (N,1,P,P,P)\n',
        'y = torch.zeros(len(patches), dtype=torch.long)           # replace!\n\n',
        'dataset = TensorDataset(X, y)\n',
        'loader  = DataLoader(dataset, batch_size=4, shuffle=True)\n\n',
        'device    = "cuda" if torch.cuda.is_available() else "cpu"\n',
        'model_    = Simple3DCNN(n_classes=2).to(device)\n',
        'criterion = nn.CrossEntropyLoss()\n',
        'optimiser = optim.Adam(model_.parameters(), lr=1e-3)\n\n',
        'for epoch in range(10):\n',
        '    total_loss = 0\n',
        '    for xb, yb in loader:\n',
        '        xb, yb = xb.to(device), yb.to(device)\n',
        '        optimiser.zero_grad()\n',
        '        loss = criterion(model_(xb), yb)\n',
        '        loss.backward()\n',
        '        optimiser.step()\n',
        '        total_loss += loss.item()\n',
        '    print(f"Epoch {epoch+1:02d}  loss={total_loss/len(loader):.4f}")',
      ],
    },
  ],
}

export default function DeepLearning({ imageId }) {
  const [downloading, setDownloading] = useState(false)

  function downloadNotebook() {
    setDownloading(true)
    const json = JSON.stringify(COLAB_NOTEBOOK, null, 2)
    const blob = new Blob([json], { type: 'application/json' })
    const url  = URL.createObjectURL(blob)
    const a    = Object.assign(document.createElement('a'), {
      href: url, download: 'MedVision_3D_CNN_Training.ipynb',
    })
    a.click()
    URL.revokeObjectURL(url)
    setTimeout(() => setDownloading(false), 1200)
  }

  const STEPS = [
    {
      num: 1,
      title: 'Upload & Inspect',
      desc: 'Upload your DICOM / NIfTI volume in the Data Manager. Check spacing, FOV, and intensity range in QC & Plots.',
    },
    {
      num: 2,
      title: 'Pre-process (optional)',
      desc: 'Apply Gaussian/Median smoothing or normalisation in the Tools section to clean the data before patching.',
    },
    {
      num: 3,
      title: 'Extract Patches',
      desc: 'Use Patchify 3D to divide the volume into cubic patches. Download the .npz file.',
    },
    {
      num: 4,
      title: 'Label your data',
      desc: 'Annotate patches externally (e.g., with ITK-SNAP or 3D Slicer). Tumour / non-tumour, healthy / pathological, etc.',
    },
    {
      num: 5,
      title: 'Train in Google Colab',
      desc: 'Download the Colab notebook below. Upload your .npz and labels, then run the cells to train a 3-D CNN or U-Net.',
    },
    {
      num: 6,
      title: 'Evaluate & Iterate',
      desc: 'Monitor training loss, compute dice/accuracy metrics, and iterate on patch size, architecture, and augmentation.',
    },
  ]

  return (
    <div className="page">
      <div className="page-header">
        <h2 className="page-title">🧬 Deep Learning</h2>
        <p className="page-desc">
          A practical integration path from medical image volumes to trained 3-D CNNs.
          Heavy training runs in Google Colab (free GPU), not on this server.
        </p>
      </div>

      {/* Pipeline steps */}
      <div className="section-label">Recommended Workflow</div>
      <div className="dl-steps" style={{ maxWidth: 680, marginBottom: '2rem' }}>
        {STEPS.map(s => (
          <div key={s.num} className="dl-step">
            <div className="dl-step-num">{s.num}</div>
            <div>
              <div className="dl-step-title">{s.title}</div>
              <div className="dl-step-desc">{s.desc}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Download Colab notebook */}
      <div className="section-label">Colab Notebook</div>
      <div className="card" style={{ maxWidth: 520 }}>
        <div className="card-header">
          <span className="card-title">📓 MedVision_3D_CNN_Training.ipynb</span>
          <span className="chip green">Free GPU</span>
        </div>
        <div className="card-body">
          <p style={{ fontSize: '.83rem', color: 'var(--text-secondary)', lineHeight: 1.65, marginBottom: '1rem' }}>
            Ready-to-run Google Colab notebook containing:
          </p>
          <ul style={{ paddingLeft: '1.1rem', fontSize: '.82rem', color: 'var(--text-secondary)', lineHeight: 2, marginBottom: '1rem' }}>
            <li>Patch loader for the exported .npz</li>
            <li>Simple 3-D CNN classifier skeleton (PyTorch)</li>
            <li>MONAI 3-D U-Net skeleton for segmentation</li>
            <li>Training loop with loss logging</li>
          </ul>
          <button className="btn btn-primary" onClick={downloadNotebook} disabled={downloading}>
            {downloading ? <><span className="spinner" /> Preparing…</> : '⬇ Download Notebook'}
          </button>
        </div>
      </div>

      {/* Note */}
      <div className="alert alert-info" style={{ maxWidth: 520, marginTop: '1.5rem' }}>
        💡 <strong>Note:</strong> This notebook provides a training skeleton.
        Replace the dummy labels with your actual annotations and tune hyperparameters
        for your specific clinical task.
      </div>
    </div>
  )
}
